name = "MPIMeasurements"
uuid = "a874a27a-e9a7-503d-98b6-bf61df4bb725"
authors = ["Tobias Knopp <tobias@knoppweb.de>"]
version = "0.1.0"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
Configurations = "5218b696-f38b-4ac9-8b61-a12ec717816d"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"
Graphics = "a2bd30eb-e257-5431-a919-1863eab51364"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
IniFile = "83e8ac13-25f8-5344-8a64-a9f2b223428f"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LibSerialPort = "a05a14c7-6e3b-5ba9-90a2-45558833e1df"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MPIFiles = "371237a9-e6c1-5201-9adb-3d8cfa78fa9f"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
RedPitayaDAQServer = "c544963a-496b-56d4-a5fe-f99a3f174c8f"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
ReusePatterns = "a39b5e78-89b5-562b-97d8-70689129df0c"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
ThreadPools = "b189fb0b-2eb5-4ed4-bc0c-d34c51242431"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
Compat = "3.25"
Graphics = "1.1"
HDF5 = "0.10,0.11,0.12,0.13,0.14,0.15"
IniFile = "0.5"
Interpolations = "0.13"
LibSerialPort = "0.3"
MPIFiles = "0.11.0"
ProgressMeter = "1.5"
RedPitayaDAQServer = "0.1, 0.2, 0.3"
Reexport = "0.2, 1.0"
ThreadPools = "1.2"
Unitful = "1.6"
Plots = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[targets]
test = ["Test", "Plots"]
